name: simple go build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: go program build
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.1'
    - run: go run hello-world.go
